before_script:
- apt-get update -qq
- apt-get install -qq bubblewrap
- apt-get install -qq unzip
- echo "" | sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)
- opam init -c 4.07.1 --root=.opam
- eval $(opam env --root=.opam --set-root)
- opam update
- opam install -y -q odoc
- opam install -y -q . --deps-only
- opam upgrade -y -q

build:
  stage: build
  script:
  - opam install -y -q .
  - dune build example/main.bc.js --profile release
  - dune build example/index.html
  - dune build example/stylesheet.css
  - dune build @doc
  artifacts:
    paths:
    - _build

pages:
  stage: deploy
  script:
  - mkdir public
  - mv _build/main/_doc/_html public/doc
  - mv _build/main/example public/example
  artifacts:
    paths:
    - public
  only:
  - master

cache:
  paths:
  - .opam
