image: ocaml/opam2:4.08

build:
  stage: build
  script:
  - opam depext conf-m4
  - opam install -y .
  - dune build example/main.bc.js --profile release
  - dune build example/index.html
  - dune build example/stylesheet.css
  - opam install -y -q odoc
  - dune build @doc
  artifacts:
    paths:
    - _build

pages:
  stage: deploy
  script:
  - mkdir public
  - mv _build/default/_doc/_html public/doc
  - mv _build/default/example public/example
  artifacts:
    paths:
    - public
  only:
  - master
